### ISSUE TITLE
Deploy to Heroku/Store theme files on Amazon S3

### ISSUE THREAD

**Issue by GarPit** [vinsol-spree-contrib/spree_themes#10]
Hey, guys.

Awesome extension!
Would like to know if you have plans for feature of storing theme files not in a local filesystem?

**Comment by PareshGupta** [comment]
Hi @GarPit,

Thanks for appreciation :)

Though we have roadmap to further enhance the extension, but we are not working on it currently. We will start with developing new feature ASAP.

If you have the PR, it would be great if you could raise it and we will be happy to merge it.
