### ISSUE TITLE
Not able to upload the theme

### ISSUE THREAD

**Issue by codevmatter** [vinsol-spree-contrib/spree_themes#13]
While uploading your theme-BigShop-master or theme-ClassicWhite-3-3-bump themes i am getting the attached error. I have following spree and vinsol related Gems
gem 'spree', '~> 3.3'

gem 'spree_auth_devise', '~> 3.3'

gem 'spree_gateway', '~> 3.3'

gem 'sprockets-helpers', '~> 1.2.1'

gem 'vinsol_spree_themes', :git => 'https://github.com/vinsol-spree-contrib/spree_themes.git', :branch => '3-3-stable'

![vinsol_theme_upload](https://user-images.githubusercontent.com/35578669/35120196-f77402a4-fc5c-11e7-856e-b2444dd19cc0.JPG)

**Comment by PareshGupta** [comment]
Hi @codevmatter, I tried uploading themes on my end and they uploaded without any errors.
I would suggest downloading the themes from below links and try uploading again.

https://github.com/vinsol-spree-contrib/theme-BigShop/archive/3-3-bump.zip
https://github.com/vinsol-spree-contrib/theme-ClassicWhite/archive/3-3-bump.zip

If you face any issues again, please let us know the steps you are following so we can debug the issue.

**Comment by codevmatter** [comment]
I am still getting the error. Could you please send me the list of all the gems that you are using for spree and your themes.

**Comment by codevmatter** [comment]
@PareshGupta - I generated a rails project and added these gems to gem file and installed them as per their installation doc.

gem 'rubyzip'
gem 'spree', '~> 3.3.0'

gem 'spree_auth_devise', '~> 3.3'

gem 'spree_gateway', '~> 3.3'

gem 'sprockets-helpers', '~> 1.2.1'

gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: '3-3-stable'

I downloaded https://github.com/vinsol-spree-contrib/theme-BigShop/archive/3-3-bump.zip
 Clicked on "ADD NEW THEME" under VINSOL SPREE THEME tab in admin (http://localhost:3000/admin/themes)

selected the downloaded zip file and got this error.

![image](https://user-images.githubusercontent.com/35578669/35201266-8458e0c0-fedf-11e7-81e1-3a5a48dda42c.png)

**Comment by PareshGupta** [comment]
Hi @codevmatter 
These are the list of gems in Gemfile we are using:-

`ruby '2.3.3'`
`gem 'rails', '~> 5.1.2'`

`gem 'spree', '~> 3.3.0'`
`gem 'spree_auth_devise', '~> 3.3'`
`gem 'spree_gateway', '~> 3.3'`

`gem 'sprockets-helpers', '~> 1.2.1'`
`gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: '3-3-stable'`

Try with these gems and let us know if you still face the issue.

**Comment by EduardoRicSan** [comment]
How Can I solve the same issue??? HELP ME PLEASE
