### ISSUE TITLE
Not able to use gem spree_yoda_theme

### ISSUE THREAD

**Issue by codevmatter** [vinsol-spree-contrib/spree_themes#14]
I am not able to install the gem as per the instruction in your github.

bundle update result
![image](https://user-images.githubusercontent.com/35578669/35120509-f698328c-fc5d-11e7-939f-6ce18b02c1f5.png)

bundle install result
![image](https://user-images.githubusercontent.com/35578669/35120573-2d6b52d0-fc5e-11e7-8965-6db0d21eebdf.png)

my gem file

![image](https://user-images.githubusercontent.com/35578669/35120919-4b3e264c-fc5f-11e7-82e6-08621a88d0a7.png)

**Comment by achalaggarwal** [comment]
@bansalakhil @PareshGupta

**Comment by PareshGupta** [comment]
@codevmatter: 
Currently `spree_yoda_theme` is not compatible for gem `spree 3.3` and `rails 5`.  
If you have the PR for upgrading to `spree 3.5`, we will be happy to merge it else we will work on it ASAP.

For your reference, currently this works on 
`gem 'rails', '4.2.7'`
`gem 'spree', '~> 3.0.8'`
`gem 'spree_auth_devise', '~> 3.0.5'`
`gem 'spree_themes', git: 'https://github.com/vinsol/spree-themes.git', branch: 'develop'`

**Comment by codevmatter** [comment]
I haven't seen spree 3.5 PR yet in the github, I see the latest as 3.4-stable.
I can't go back to spree 3.0.8. So if you can give me the gems for the latest and greatest spree branch, it would be helpful.

**Comment by codevmatter** [comment]
or give a theme that would work on my current gems.

**Comment by PareshGupta** [comment]
@codevmatter: Checkout these themes which are supported for your current gems. 

https://github.com/vinsol-spree-contrib/theme-BigShop/archive/3-3-bump.zip
https://github.com/vinsol-spree-contrib/theme-ClassicWhite/archive/3-3-bump.zip

Download them and upload it from the spree admin interface to use them. Also i would suggest to remove the `spree_yoda_theme` from your gemfile.

Let us know incase you have face any issues.
