### ISSUE TITLE
undefined local variable or method 'cache_key_for_taxons' with spree 3.4.4

### ISSUE THREAD

**Issue by jungbunzlav** [vinsol-spree-contrib/spree_themes#17]
I am using **spree 3.4.4** and **vinsol_spree_themes 0.0.1 (at master@5c5b7a0)** and I am getting the error:

```
undefined local variable or method `cache_key_for_taxons' for #<#<Class:0x00007f7ef06747f8>:0x00007f7ef0643d60>
Did you mean?  cache_key_for_products
```

Is there any way around this issue?

**Comment by PareshGupta** [comment]
Hi @jungbunzlav I would suggest you to use branch `3-4-bump` which is compatible for `spree >= 3.4`
 Also, let us know if you still face the issue.

**Comment by jungbunzlav** [comment]
Sorry, but using vinsol_spree_themes 0.0.1 (at 3-4-bump@88dd642) still raises the above issue.

**Comment by PareshGupta** [comment]
@jungbunzlav 
After you `bundle` to **3-4-bump** branch, follow the below steps:-
1. Delete the `default` directory in your application path
  `public/vinsol_spree_themes/default`
2. Then, again install the vinsol_spree_themes
  `bundle exec rails g vinsol_spree_themes:install`
3. Finally, restart the server.

I hope this solves the issue.

**Comment by raunjon** [comment]
gem 'spree', '~> 3.5'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
# gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: 'master'
gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: '3-4-bump'
gem 'spree_analytics_trackers'

Did this, still getting the issue

> @jungbunzlav
> After you `bundle` to **3-4-bump** branch, follow the below steps:-
> 
> 1. Delete the `default` directory in your application path
>    `public/vinsol_spree_themes/default`
> 2. Then, again install the vinsol_spree_themes
>    `bundle exec rails g vinsol_spree_themes:install`
> 3. Finally, restart the server.
> 
> I hope this solves the issue.
