### ISSUE TITLE
Error while mail is sent on order complete by user

### ISSUE THREAD

**Issue by guptalakshya92** [vinsol-spree-contrib/spree_themes#21]
[ActiveJob] [ActionMailer::DeliveryJob] [ebf3dc68-887c-4dc2-ab46-c9021adb22dc] Spree::OrderMailer#confirm_email: processed outbound mail in 1930.0ms
  Rendered public/vinsol_spree_themes/current/views/spree/shared/_translations.html.erb (0.8ms)
[ActiveJob] [ActionMailer::DeliveryJob] [ebf3dc68-887c-4dc2-ab46-c9021adb22dc] Error performing ActionMailer::DeliveryJob (Job ID: ebf3dc68-887c-4dc2-ab46-c9021adb22dc) from Async(mailers) in 1932.0ms: ActionView::Template::Error (undefined method `cookies' for #<Spree::OrderMailer:0x00007fafc9a0ae08>):
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/controller_helper.rb:14:in `cookies'
/Users/lakshya/.rvm/gems/ruby-2.4.2/bundler/gems/spree_themes-0b8801fe8f35/config/initializers/sprockets.rb:66:in `preview_by_admin?'
/Users/lakshya/.rvm/gems/ruby-2.4.2/bundler/gems/spree_themes-0b8801fe8f35/config/initializers/sprockets.rb:58:in `current_theme'
/Users/lakshya/.rvm/gems/ruby-2.4.2/bundler/gems/spree_themes-0b8801fe8f35/config/initializers/sprockets.rb:39:in `initialize'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:252:in `new'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:252:in `block in asset_resolver_strategies'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:251:in `map'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:251:in `asset_resolver_strategies'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/asset_url_helper.rb:198:in `asset_path'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/asset_url_helper.rb:373:in `image_path'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/asset_tag_helper.rb:232:in `image_tag'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/spree_core-3.4.4/app/views/spree/shared/_base_mailer_header.html.erb:16:in `block in _97b3f658a139044822aa69b23cf1dc9d'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:39:in `capture'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/tag_helper.rb:272:in `content_tag'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/url_helper.rb:198:in `link_to'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/spree_core-3.4.4/app/views/spree/shared/_base_mailer_header.html.erb:15:in `_97b3f658a139044822aa69b23cf1dc9d'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:157:in `block in render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:352:in `instrument_render_template'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:155:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/partial_renderer.rb:310:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:47:in `render_partial'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:21:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/spree_core-3.4.4/app/views/layouts/spree/base_mailer.html.erb:13:in `_5b39332459e0ece807e10eb9917a7918'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:157:in `block in render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:352:in `instrument_render_template'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/template.rb:155:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:14:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:23:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/rendering.rb:103:in `_render_template'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/rendering.rb:83:in `render_to_body'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/rendering.rb:24:in `render'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:935:in `block in collect_responses_from_templates'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:932:in `each'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:932:in `each'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:932:in `map'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:932:in `collect_responses_from_templates'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:917:in `collect_responses'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:830:in `mail'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/spree_core-3.4.4/app/mailers/spree/base_mailer.rb:19:in `mail'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/spree_core-3.4.4/app/mailers/spree/order_mailer.rb:7:in `confirm_email'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/rescuable.rb:23:in `block in process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/rescuable.rb:22:in `process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:609:in `block in process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/base.rb:608:in `process'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/message_delivery.rb:104:in `tap'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/actionmailer-5.1.4/lib/action_mailer/delivery_job.rb:14:in `perform'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/execution.rb:37:in `block in perform_now'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/logging.rb:44:in `block in tag_logger'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/logging.rb:44:in `tag_logger'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/execution.rb:33:in `perform_now'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/execution.rb:22:in `block in execute'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/execution.rb:20:in `execute'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/activejob-5.1.4/lib/active_job/queue_adapters/async_adapter.rb:68:in `perform'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/lakshya/.rvm/gems/ruby-2.4.2/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
  Rendered public/vinsol_spree_themes/current/views/spree/shared/_head.html.erb 

**# Not able to send mail as user purchase something in spree 3.4.4**

**Comment by himanshumishra31** [comment]
Hi @guptalakshya92 

This doesn't seem to be an issue of this extension. It seems like there is some problem in your mail config. You can confirm it by using letter opener gem https://github.com/ryanb/letter_opener. 

Thank You.

**Comment by PareshGupta** [comment]
@guptalakshya92  We are closing this issue.
Feel free to open any other issues related to extensions in future. :)
