### ISSUE TITLE
Theme upload not working

### ISSUE THREAD

**Issue by jjf21** [vinsol-spree-contrib/spree_themes#6]
Can't use theme:
1. Snapshot not displaying
2. Preview display the current (default) theme
3. Template, show empty page

**GEMS**
```
gem 'sprockets-helpers', '~> 1.2.1'
gem 'spree', '~> 3.3.0'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
gem 'globalize', github: 'globalize/globalize'
gem 'activemodel-serializers-xml'
gem 'vinsol_spree_themes'
```

<img width="1280" alt="capture d ecran 2017-09-09 a 23 27 57" src="https://user-images.githubusercontent.com/29787388/30244129-3be19494-95b8-11e7-8ac7-0d7d5b0f5617.png">
<img width="1280" alt="capture d ecran 2017-09-09 a 23 44 03" src="https://user-images.githubusercontent.com/29787388/30244160-d3204206-95b8-11e7-8018-45b8320764de.png">

**Comment by marcfuentes** [comment]
Same error in my setup, any fix?

**Comment by sawangupta92** [comment]
It seems that you have compressed the entire directory “theme-ClassicWhite-master”, instead you should compress the contents of “theme-ClassicWhite-master”.

Let me know if you are still facing the same issue.

**Comment by PareshGupta** [comment]
@marcfuentes This issue has been fixed now, also i hope it's working fine for you as well.
We are closing this issue
