### ISSUE TITLE
not uploading,Template file invalid 

### ISSUE THREAD

**Issue by nadh44** [vinsol-spree-contrib/spree_themes#8]
![fireshot capture 35 - spree administration_ themes_ - http___vinsol-spree-themes-demo do](https://user-images.githubusercontent.com/18110247/31172238-68cd23d0-a920-11e7-8cbe-d90db59196fd.png)..
  I did follow your documentation.

**Comment by bhaskarvgurram** [comment]
I am also facing the same issue

**Comment by nadh44** [comment]
i think have a error in extension, i did view customization by manual 
    On Sunday, October 8, 2017, 12:56:15 AM GMT+5:30, bhaskarvgurram <notifications@github.com> wrote:  
 
 
I am also facing the same issue

**Comment by tanmay3011** [comment]
@nadh44, @bhaskarvgurram  Can you please share what changes you have made to themes and what steps you have followed.
As well as if you can share the zip file, I can try to replicate the issue at my end and add a fix for it.

**Comment by nadh44** [comment]
I have added the vinsol_spree_theme  sample templates zip files

**Comment by nadh44** [comment]
![fireshot capture 43 - vinsol-spree-contrib_s_ - https___github com_vinsol-spree-contrib_spree_themes](https://user-images.githubusercontent.com/18110247/31423254-4200c6de-ae71-11e7-9ce2-c4ed

my followed 
steps

**Comment by nadh44** [comment]
![fireshot capture 43 - vinsol-spree-contrib_s_ - https___github com_vinsol-spree-contrib_spree_themes](https://user-images.githubusercontent.com/18110247/31423346-e9027aae-ae71-11e7-8357-38afb94c14e0.png)

**Comment by nadh44** [comment]
I have  followed these steps

**Comment by tanmay3011** [comment]
@nadh44 Can you share the theme which you're trying to upload as I could see some themes(i.e. default and crown-theme) uploaded in the above the image.

**Comment by nadh44** [comment]
crown-theme ...firstly crown-theme cloned by GitHub and unzipped the cloned file and later zipped and tried to uploading.

**Comment by nadh44** [comment]
![screenshot 204](https://user-images.githubusercontent.com/18110247/31440366-4248b41c-aead-11e7-9744-7412eae717db.png)

**Comment by nadh44** [comment]
this is the template format inside the crown-theme.

**Comment by tanmay3011** [comment]
@nadh44 This seems to be a uploading issue through Windows System. 
Since you're uploading from a windows system, I guess you're facing this `file` related `paperclip` issue. 
Solution is given [here](https://github.com/thoughtbot/paperclip/#file). Can you please check if this resolves your problem.

**Comment by PareshGupta** [comment]
@nadh44 Hi, I hope the issue has been resolved at your end now. We are closing the issue.
If you face any other related issues, feel free to raise one here. :)
