### ISSUE TITLE
Theme not being applied after compile and publish

### ISSUE THREAD

**Issue by ashishcompwiz** [vinsol-spree-contrib/spree_themes#9]
Hi installed the spree_themes extension to spree 3.3.1 and then added ur theme bigshop (master branch)
It adds, compiles and publishes successfully in admin. but when i check any of the pages in frontend its not being applied. they are still on default theme. although the theme is applied when in preview mode.
i am in development mode and config.assets.debug is set to false.

**Comment by tanmay3011** [comment]
Hi @ashishcompwiz 
Can you add a snapshot of the admin/theme page as well as can you please check the state attribute of the theme in the db. Is it published?

**Comment by tanmay3011** [comment]
This seems to be working fine so closing this one.
